In [1]:
import warnings
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sqlalchemy import text
from sqlalchemy.engine import create_engine
from sqlalchemy.orm import sessionmaker

pd.set_option('display.max_columns', None)

In [2]:
class DataBaseSession:
    def __init__(self) -> None:
        self.db_user = 'root'
        self.db_password = 'rushi12345'
        self.db_host = '192.168.29.7'
        self.db_name = 'data_prac_db'
    
    def LocalSession(self):
        engine = create_engine(f"mysql+pymysql://{self.db_user}:{self.db_password}@{self.db_host}/{self.db_name}")
        SessionLocal = sessionmaker(autoflush=True, bind=engine)
        return SessionLocal()

In [3]:
session = DataBaseSession()
db = session.LocalSession()

In [4]:
class SQL5:
    def __init__(self) -> None:
        pass
    
    def query(self, query:str) -> pd.DataFrame:
        return pd.DataFrame(db.execute(text(query)).fetchall())

In [5]:
data = SQL5()

In [6]:
data.query("""
show tables;
""")

  Tables_in_data_prac_db
0           bank_details
1              bank_view
2             dress_data
3           supply_chain

In [7]:
data.query("""
show databases;
""")

             Database
0        data_prac_db
1  information_schema
2               mysql
3  performance_schema
4                 sys
5        user_service

* Allowed file size = 1048576 = 1 MB
```sql
set global max_allowd_packet = 200 * 1048576 = 20971520
```

In [8]:
data.query("""
select * from supply_chain limit 5;
""")

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,PQ First Sent to Client Date,PO Sent to Vendor Date,Scheduled Delivery Date,Schedule Delivery Date New,Delivered to Client Date,Delivered to Client Date New,Delivery Recorded Date,Delivery Recorded Date New,delivery_recorded_day,delivery_recorded_month,delivery_recorded_year,Product Group,Sub Classification,Vendor,Item Description,Molecule/Test Type,Brand,Dosage,Dosage Form,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,actual_price,Discount(%),discount_flag,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,CÃ´te d'Ivoire,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,2-Jun-06,2006-06-02,2-Jun-06,2006-06-02,2-Jun-06,2006-06-02,2,6,2006,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,"HIV, Reveal G3 Rapid HIV-1 Antibody Test, 30 T...","HIV, Reveal G3 Rapid HIV-1 Antibody Test",Reveal,None,Test kit,30,19,551.0,29.00,29.1,0.343644,Yes,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,None
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,14-Nov-06,2006-11-14,14-Nov-06,2006-11-14,14-Nov-06,2006-11-14,14,11,2006,ARV,Pediatric,Aurobindo Pharma Limited,"Nevirapine 10mg/ml, oral suspension, Bottle, 2...",Nevirapine,Generic,10mg/ml,Oral suspension,240,1000,6200.0,6.20,7.2,13.888900,Yes,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,None
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,CÃ´te d'Ivoire,PMO - US,Direct Drop,FCA,Air,Pre-PQ Process,Date Not Captured,27-Aug-06,2006-08-27,27-Aug-06,2006-08-27,27-Aug-06,2006-08-27,27,8,2006,HRDT,HIV test,Abbott GmbH & Co. KG,"HIV 1/2, Determine Complete HIV Kit, 100 Tests","HIV 1/2, Determine Complete HIV Kit",Determine,None,Test kit,100,500,40000.0,80.00,80.0,0.000000,No,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,None
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,1-Sep-06,2006-09-01,1-Sep-06,2006-09-01,1-Sep-06,2006-09-01,1,9,2006,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,"Lamivudine 150mg, tablets, 60 Tabs",Lamivudine,Generic,150mg,Tablet,60,31920,127360.8,3.99,4.2,5.000000,Yes,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,None
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,11-Aug-06,2006-08-11,11-Aug-06,2006-08-11,11-Aug-06,2006-08-11,11,8,2006,ARV,Adult,Aurobindo Pharma Limited,"Stavudine 30mg, capsules, 60 Caps",Stavudine,Generic,30mg,Capsule,60,38000,121600.0,3.20,3.0,-6.666670,No,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,None

* Procedure

```sql
DELIMITER &&
CREATE PROCEDURE getInfoByJob(IN param VARCHAR(255))
BEGIN
    SELECT * FROM bank_details WHERE job = param;
END &&
DELIMITER ;
```

* Function
```sql
DELIMITER $$

CREATE FUNCTION add_to_col(a INT)
RETURNS INT
DETERMINISTIC
BEGIN
   DECLARE b INT;
   SET b = a + 10;
   RETURN b;
END $$

DELIMITER ;
```

In [9]:
data.query("""
select balance, add_to_col(balance) from bank_details  limit 5;
""")

   balance  add_to_col(balance)
0     2143                 2153
1       29                   39
2        2                   12
3     1506                 1516
4        1                   11

In [10]:
data.query("""
select * from supply_chain limit 5;
""")

,ID,Project Code,PQ #,PO / SO #,ASN/DN #,Country,Managed By,Fulfill Via,Vendor INCO Term,Shipment Mode,PQ First Sent to Client Date,PO Sent to Vendor Date,Scheduled Delivery Date,Schedule Delivery Date New,Delivered to Client Date,Delivered to Client Date New,Delivery Recorded Date,Delivery Recorded Date New,delivery_recorded_day,delivery_recorded_month,delivery_recorded_year,Product Group,Sub Classification,Vendor,Item Description,Molecule/Test Type,Brand,Dosage,Dosage Form,Unit of Measure (Per Pack),Line Item Quantity,Line Item Value,Pack Price,actual_price,Discount(%),discount_flag,Unit Price,Manufacturing Site,First Line Designation,Weight (Kilograms),Freight Cost (USD),Line Item Insurance (USD)
0,1,100-CI-T01,Pre-PQ Process,SCMS-4,ASN-8,CÃ´te d'Ivoire,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,2-Jun-06,2006-06-02,2-Jun-06,2006-06-02,2-Jun-06,2006-06-02,2,6,2006,HRDT,HIV test,RANBAXY Fine Chemicals LTD.,"HIV, Reveal G3 Rapid HIV-1 Antibody Test, 30 T...","HIV, Reveal G3 Rapid HIV-1 Antibody Test",Reveal,None,Test kit,30,19,551.0,29.00,29.1,0.343644,Yes,0.97,Ranbaxy Fine Chemicals LTD,Yes,13,780.34,None
1,3,108-VN-T01,Pre-PQ Process,SCMS-13,ASN-85,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,14-Nov-06,2006-11-14,14-Nov-06,2006-11-14,14-Nov-06,2006-11-14,14,11,2006,ARV,Pediatric,Aurobindo Pharma Limited,"Nevirapine 10mg/ml, oral suspension, Bottle, 2...",Nevirapine,Generic,10mg/ml,Oral suspension,240,1000,6200.0,6.20,7.2,13.888900,Yes,0.03,"Aurobindo Unit III, India",Yes,358,4521.5,None
2,4,100-CI-T01,Pre-PQ Process,SCMS-20,ASN-14,CÃ´te d'Ivoire,PMO - US,Direct Drop,FCA,Air,Pre-PQ Process,Date Not Captured,27-Aug-06,2006-08-27,27-Aug-06,2006-08-27,27-Aug-06,2006-08-27,27,8,2006,HRDT,HIV test,Abbott GmbH & Co. KG,"HIV 1/2, Determine Complete HIV Kit, 100 Tests","HIV 1/2, Determine Complete HIV Kit",Determine,None,Test kit,100,500,40000.0,80.00,80.0,0.000000,No,0.80,ABBVIE GmbH & Co.KG Wiesbaden,Yes,171,1653.78,None
3,15,108-VN-T01,Pre-PQ Process,SCMS-78,ASN-50,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,1-Sep-06,2006-09-01,1-Sep-06,2006-09-01,1-Sep-06,2006-09-01,1,9,2006,ARV,Adult,SUN PHARMACEUTICAL INDUSTRIES LTD (RANBAXY LAB...,"Lamivudine 150mg, tablets, 60 Tabs",Lamivudine,Generic,150mg,Tablet,60,31920,127360.8,3.99,4.2,5.000000,Yes,0.07,"Ranbaxy, Paonta Shahib, India",Yes,1855,16007.06,None
4,16,108-VN-T01,Pre-PQ Process,SCMS-81,ASN-55,Vietnam,PMO - US,Direct Drop,EXW,Air,Pre-PQ Process,Date Not Captured,11-Aug-06,2006-08-11,11-Aug-06,2006-08-11,11-Aug-06,2006-08-11,11,8,2006,ARV,Adult,Aurobindo Pharma Limited,"Stavudine 30mg, capsules, 60 Caps",Stavudine,Generic,30mg,Capsule,60,38000,121600.0,3.20,3.0,-6.666670,No,0.05,"Aurobindo Unit III, India",Yes,7590,45450.08,None

```sql
DELIMITER $$

CREATE FUNCTION  final_profits(profit int, discount int)
returnts int
DETERMINSTIC
begin
  declare final_profit int;
  set final_profit = profit - discount;
  return final_profilt;
end $$
DELIMETER;
```

```sql
DELIMITER $$

CREATE FUNCTION discount(pack float, actual float)
returns float
deterministic
begin
   declare discount float;
   set discount = actual - pack;
   return discount;
end $$

DELIMITER ;
```

```sql
DELIMITER $$

CREATE FUNCTION discount(pack decimal(20, 6), actual decimal(20, 6))
returns float
deterministic
begin
   declare discount float;
   set discount = actual - pack;
   return discount;
end $$

DELIMITER ;
```

In [11]:
data.query("""
select max(`Line Item Value`), min(`Line Item Value`) from supply_chain;
""")

   max(`Line Item Value`)  min(`Line Item Value`)
0               5951990.4                     0.0

```sql
DELIMITER $$
create function  mark_sales(sales decimal(20, 6))
returns varchar(30)
deterministic
begin
   declare flag_sales varchar(30);
   if sales <= 1000 then 
       set flag_sales = "super affordable";
   elseif sales > 1000 and sales <= 3000 then
       set flag_sales = "affordable" ;
   elseif sales > 3000 and sales <= 6000 then
       set flag_sales = "moderate";
   else
       set flag_sales = "expensive";
   end if;
   return flag_sales;
end $$
DELIMITER ;
```

In [12]:
data.query("""
select mark_sales(`Line Item Value`) from supply_chain limit 5;
""")

  mark_sales(`Line Item Value`)
0              super affordable
1                     expensive
2                     expensive
3                     expensive
4                     expensive

In [22]:
data.query("""
select mark_sales(1000)
""")

   mark_sales(1000)
0  super affordable

```sql
create table loop_table(val int)

DELIMITER &&

CREATE PROCEDURE GenerateData()
BEGIN
    SET @var = 10;
    generate_data: LOOP
        INSERT INTO loop_table values(@var);
        SET @var = @var + 1;
        IF @var = 100 THEN
            LEAVE generate_data;
        END IF;
    END LOOP generate_data;
END &&

DELIMITER ;

call GenerateData()
```